[package]
name = "indominiso/clientcast"
version = "1.0.7"
description = "ClientCast with wally support"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "Apache-2.0"
authors = ["Pyseps"]

[dependencies]
